### ISSUE TITLE
Test: Bring up lineage-15.1

### ISSUE THREAD

**Issue by Quallenauge** [Quallenauge/Yoga-Tab-3-Plus-Issue-Tracker#1]
It should be tested:

The current firmware is able to launch at the device.
The current firmware should not have device specific errors (like missing firmware / configuration files, which are available for the L-version).

**Comment by vladimiroltean** [comment]
Is there anything left to do here?

**Comment by Quallenauge** [comment]
Actually it needs to be tested on a F device. After that, I think we can close this issue.

**Comment by Quallenauge** [comment]
This issue was moved to Lenovo-YTX703-Devel/android_device_lenovo_YTX703-common#25
