### ISSUE TITLE
lpm_levels.sleep_disabled=1 in kernel cmdline?

### ISSUE THREAD

**Issue by vladimiroltean** [Quallenauge/Yoga-Tab-3-Plus-Issue-Tracker#11]
What does this setting do exactly? (code is under [drivers/cpuidle/lpm-levels.c](https://github.com/vladimiroltean/android_kernel_lenovo_msm8976/blob/cm-14.1-caf-LA.BR.1.3.6-04510-8976.0/drivers/cpuidle/lpm-levels.c#L522))
Why was it needed originally, in the stock kernel?
Is it still needed now?
Is there any energy saving improvement associated with removing this boot setting?

**Comment by Gabriel85** [comment]
Good question, always wondered about that too.. It is in the stock and also used on other kernels. But it is not needed to boot..
I don't now if it saves any energy, but it doesn't seem to break anything if it's not there..
We could remove it and see if it causes any problem in the long run?

**Comment by vladimiroltean** [comment]
I removed it. My cat still lives.

**Comment by Gabriel85** [comment]
Good, if you have no issues and battery life stays the same, we can get rid of it... :)

**Comment by vladimiroltean** [comment]
A week later and still did not notice any difference. Closing for now.

**Comment by Gabriel85** [comment]
Me neither, guess it is not needed... But many devices use it (or even all?), and it affects the CPU on a very deep level. So I guess it is sound to keep testing it for a couple of weeks/months and see what happens?

**Comment by vladimiroltean** [comment]
Update: sleep seems to be disabled at boot time, and then re-enabled once the boot process is over.
See the init scripts from the CAF repo: https://source.codeaurora.org/quic/la/device/qcom/common/tree/rootdir/etc/init.qcom.post_boot.sh?h=LA.BR.1.3.7_rb1.11 (search for sleep_disabled).
