### ISSUE TITLE
Update to latest CAF kernel tag

### ISSUE THREAD

**Issue by vladimiroltean** [Quallenauge/Yoga-Tab-3-Plus-Issue-Tracker#12]
As of today, latest [CAF tags](https://wiki.codeaurora.org/xwiki/bin/QAEP/release) for msm8952_64 are:

- [LA.BR.1.3.6-05410-8976.0](https://source.codeaurora.org/quic/la/kernel/msm-3.10/tree/?h=LA.BR.1.3.6-05410-8976.0) (for 7.1.2)
- [LA.BR.1.3.7-03510-8976.0](https://source.codeaurora.org/quic/la/kernel/msm-3.10/tree/?h=LA.BR.1.3.7-03510-8976.0) (for 8.0.0)

**Comment by Quallenauge** [comment]
Outdated.

**Comment by Quallenauge** [comment]
Outdated
