### ISSUE TITLE
Cleanup leftovers from the Samsung repos

### ISSUE THREAD

**Issue by vladimiroltean** [Quallenauge/Yoga-Tab-3-Plus-Issue-Tracker#14]
Excerpt from the Gitter thread:
> @vladimiroltean: wtf is going on in `device/lenovo/msm8976-common/rootdir/etc/ueventd.qcom.rc`?!
> @vladimiroltean:
> ```
> commit 2cda780f4ca565d78f62078c87ad79a74c23a76c
> Author: Christian Ciach christian.ciach@gmail.com
> Date: Wed Jan 25 18:12:35 2017 +0100
> 
> Initial tree based on android_device_samsung_msm8976-common
> ```
> @vladimiroltean: got my answer right there....
> @Gabriel85: yeah old Samsung stuff.. I plan to remove those if possible, since I don't see any sense to have Samsung code on a Lenovo device without a good reason. I'd say we replace it with stuff from Lenovo, since it is closer to original QC code and produces less error messages..

**Comment by Gabriel85** [comment]
Here are the original CAF inits, some other useful tools and the code of some blobs:
https://source.codeaurora.org/quic/la/device/qcom/common/tree/?h=LA.BR.1.3.7_rb1.8

Although it seems that the inits are somehow generated?

**Comment by Quallenauge** [comment]
I think we are in good shape now.
