### ISSUE TITLE
Reduce DT2W power consumption in sleep

### ISSUE THREAD

**Issue by vladimiroltean** [Quallenauge/Yoga-Tab-3-Plus-Issue-Tracker#16]
Proposed solution: search the iio subsystem (accelerometer sensor) for a device with wakeup irq to hook into. Disable the dt2w driver after a period of idle time, and then use the accelerometer's irq to re-enable dt2w.

**Comment by Gabriel85** [comment]
That wouldn't save any power if it's in a backpack or so. But the accelerometer could be used for the complete detection, although I never have seen another implementation of this.

**Comment by Quallenauge** [comment]
This issue was moved to Lenovo-YTX703-Devel/android_device_lenovo_YTX703-common#23
