### ISSUE TITLE
Add adb and fastboot

### ISSUE THREAD

**Issue by Gabriel85** [Quallenauge/Yoga-Tab-3-Plus-Issue-Tracker#19]
Could we add adb and fastboot binaries please, like it used to be in the good old days? So people could use it for there phones without a PC (e.g. ADB over LAN to remote control the terminal).
https://github.com/LineageOS/android_system_core/tree/lineage-15.1/adb
https://github.com/LineageOS/android_system_core/tree/lineage-15.1/fastboot

**Comment by vladimiroltean** [comment]
Adb and fastboot *clients*? Sure, that would be cool to have!

**Comment by Quallenauge** [comment]
Continued here:
https://github.com/Lenovo-YTX703-Devel/android_device_lenovo_YTX703-common/issues/18
