### ISSUE TITLE
Log spammed by "WifiHAL : Received LOG message with insufficent length"

### ISSUE THREAD

**Issue by vladimiroltean** [Quallenauge/Yoga-Tab-3-Plus-Issue-Tracker#20]
This message is generated from [hardware/qcom/wlan-caf/qcwcn/wifi_hal/wifilogger_diag.cpp](https://github.com/LineageOS/android_hardware_qcom_wlan/blob/lineage-15.1/qcwcn/wifi_hal/wifilogger_diag.cpp#L2241). I don't understand what it means, though.
How can we silence it?

**Comment by vladimiroltean** [comment]
Solved by updating the wifi kernel driver.

**Comment by Quallenauge** [comment]
Cool. I try to integrate your patches within my kernel copy and give it a try.
Updated: I see, gabriel has partly integrated the wifi kernel driver as well.

BTW: Is the config item `CONFIG_PRIMA_WLAN_MDNS_OFFLOAD_SUPPORT`
really needed? I can't any usage at the kernel tree....

**Comment by vladimiroltean** [comment]
Mi scudi. It should have been `CONFIG_MDNS_OFFLOAD_SUPPORT`. Let me fix it.

**Comment by Quallenauge** [comment]
Should I do the Kconfig commit?

**Comment by Gabriel85** [comment]
I'm not getting this message. Is it in dmesg? And which version are you using?

**Comment by Quallenauge** [comment]
Gabriel, you have the latest wifi driver included in your kernel. Therefore you won't see this message. (I din't see this either).
