### ISSUE TITLE
Rework device trees to use more Open-Source alternatives to BLOBs

### ISSUE THREAD

**Issue by Quallenauge** [Quallenauge/Yoga-Tab-3-Plus-Issue-Tracker#4]
It seems the sony developers does a good job at handling their devices.
Take these trees (device/vendor) as template for the lenovo devices.
The device, which is closest to our device, seems the device-sony-**tone**.

**Comment by Gabriel85** [comment]
Open Source Power HAL (current blob not really working):
https://github.com/sonyxperiadev/device-sony-common/tree/master/hardware/power
https://github.com/sonyxperiadev/device-sony-common/tree/master/hardware/librqbalance

OS Sensor HAL (maybe incompatible with some of our sensors):
https://github.com/LineageOS/android_hardware_sony_DASH

OS Thermal Manager (needs new xml configs written, and maybe kernel-patches):
https://github.com/LineageOS/android_hardware_sony_thermanager

OS Location APIs (not sure if that is a substitute for some of our blobs?)
https://github.com/LineageOS/android_vendor_qcom_opensource_location/

Is there other useful stuff?

**Comment by Quallenauge** [comment]
This issue was moved to Lenovo-YTX703-Devel/android_device_lenovo_YTX703-common#19
