### ISSUE TITLE
Do we have Qualcomm Quick Charge supported?

### ISSUE THREAD

**Issue by vladimiroltean** [Quallenauge/Yoga-Tab-3-Plus-Issue-Tracker#8]
That is to say, somebody must understand the following commits:

- [lenovo: power: changes over CAF tag LA.BR.1.3.4-06610-8976.0](https://github.com/vladimiroltean/android_kernel_lenovo_msm8976/commit/06f85266265f4d5e90df79256c870c04584d9bf0)
- [lenovo: drivers/misc: changes over CAF tag LA.BR.1.3.4-06610-8976.0](https://github.com/vladimiroltean/android_kernel_lenovo_msm8976/commit/dce0c5fbce4e94c13cc37dd05406ad8cd7695828)
- [lenovo: drivers/usb: changes over CAF tag LA.BR.1.3.4-06610-8976.0](https://github.com/vladimiroltean/android_kernel_lenovo_msm8976/commit/3c8c99c6431cd1ca0db52c08d7e02681a395cd8c)

How much of the above commits is really needed? How much can be reverted? How does QC work? Are we missing any userspace components?

Also, I get some interesting messages at boot, that I'd like to be able to decipher:

```
[    8.338511] fusb301 8-0021: fusb301 not support
[    8.343016] fusb301: probe of 8-0021 failed with error -107
[    8.348632] fusb30x_probe start
[    8.351620] fusb302 2-0022: fusb30x_probe
[    8.355716] i2c-msm-v2 78b6000.i2c: NACK: slave not responding, ensure its powered: msgs(n:2 cur:0 tx) bc(rx:1 tx:1) mode:FIFO slv_addr:0x22 MSTR_STS:0x091343c8 OPER:0x00000010
[    8.371417] fusb302 2-0022: fusb_I2C_ReadData - Unexpected I2C error reading byte data. Address: '0x01', Return: '-107'.  Attempt #0 / 3...
[    8.383966] i2c-msm-v2 78b6000.i2c: NACK: slave not responding, ensure its powered: msgs(n:2 cur:0 tx) bc(rx:1 tx:1) mode:FIFO slv_addr:0x22 MSTR_STS:0x091343c8 OPER:0x00000010
[    8.399614] fusb302 2-0022: fusb_I2C_ReadData - Unexpected I2C error reading byte data. Address: '0x01', Return: '-107'.  Attempt #1 / 3...
[    8.412211] i2c-msm-v2 78b6000.i2c: NACK: slave not responding, ensure its powered: msgs(n:2 cur:0 tx) bc(rx:1 tx:1) mode:FIFO slv_addr:0x22 MSTR_STS:0x011383c8 OPER:0x00000010
[    8.427821] fusb302 2-0022: fusb_I2C_ReadData - Unexpected I2C error reading byte data. Address: '0x01', Return: '-107'.  Attempt #2 / 3...
[    8.440343] i2c-msm-v2 78b6000.i2c: NACK: slave not responding, ensure its powered: msgs(n:2 cur:0 tx) bc(rx:1 tx:1) mode:FIFO slv_addr:0x22 MSTR_STS:0x091343c8 OPER:0x00000010
[    8.456031] fusb302 2-0022: fusb_I2C_ReadData - Unexpected I2C error reading byte data. Address: '0x01', Return: '-107'.  Attempt #3 / 3...
[    8.468538] FUSB  fusb_IsDeviceValid - Error: Could not communicate with device over I2C!
[    8.476613] fusb302 2-0022: FUSB  fusb30x_probe - Error: Unable to communicate with device!
[    8.484997] fusb302: probe of 2-0022 failed with error -5
[    8.490460] fusb30x_probe start
[    8.493455] fusb302 8-0022: fusb30x_probe
[    8.502545] fusb302 8-0022: FUSB  fusb30x_probe - FUSB30X Driver loaded successfully!
[    8.506268] zou_hao: 4,28,40, 0,81,28,81*******
[    8.506270] ****
```

**Comment by Gabriel85** [comment]
fusb302 and everything charger related. Everything if you don't need OTG and charging... QC is not related to hat directly. No we don't missing software, there is just no fusb301 on the board.
Already cleaned up that stuff! Will push it to git as soon as I have cleaned up my repo.

**Comment by vladimiroltean** [comment]
The charging controller we have is a Texas Instruments bq25892. It does support QC 3.0 HVDCP (High Voltage Dedicated Charging Port). Datasheet for the charging controller [here](http://www.ti.com/lit/ds/symlink/bq25892.pdf), and a more generic app note is [here](http://www.ti.com/lit/an/slua786/slua786.pdf).
Don't know a lot more at the moment.

**Comment by Gabriel85** [comment]
Whats the problem? Isn't it working? It should, but I never tested it.
Yes it supports it and it surly does under stock, since there is even a QC 2.0 charger included (although they didn't bother to get it certified).

**Comment by Gabriel85** [comment]
OK I have to correct myself: our tablet does not support QC! Also HVDCP is not the same as QC. QC is rather an QC proprietary implementation of HVDCP. Fast charging only works with the included charger, and probably with some other special charger, e.g. from Samsung or Motorola; but not with Qualcomm certified QC chargers. Although I can't 100% exclude that software support is somehow possible..

**Comment by vladimiroltean** [comment]
Do share any relevant materials on the subject.

**Comment by Quallenauge** [comment]
This issue was moved to Lenovo-YTX703-Devel/android_device_lenovo_YTX703-common#21
