### ISSUE TITLE
Merge msm8976-common + YTX703F + YTX703L into single set of repos (YTX703)

### ISSUE THREAD

**Issue by vladimiroltean** [Quallenauge/Yoga-Tab-3-Plus-Issue-Tracker#9]
Both the vendor and the device set of repos should be merged (with histories preserved if possible) by adding the necessary "if" conditions to the Makefiles.
The kernel repository could also benefit from a rename to `android_kernel_lenovo_YTX703`.
Nobody minds if the F device contains a few more blobs than strictly needed, so reducing the F's space footprint to a minimum is not a goal at this point, but instead maintainability over the longer term.

**Comment by Gabriel85** [comment]
I already proposed merging the repos, but Quallenauge disagreed. He already got rid of 2 vendor repos.
My kernel-repo already has that name, and we plan to make a new git-account with a central place for all the stable repos, as soon as everything is stable.
I think both builds already are equal in everything, but a few firmware files.

**Comment by vladimiroltean** [comment]
This is a preliminary version of what a common device repository would look like:
https://github.com/vladimiroltean/android_device_YTX703
Notice the need for a build system patch to support this: https://github.com/vladimiroltean/android_device_YTX703/blob/cm-14.1/0001-allow-products-to-be-decoupled-from-a-device-folder-.patch.
I would appreciate comments on whether we can try to push this on the LineageOS Gerrit.

**Comment by vladimiroltean** [comment]
https://review.lineageos.org/#/c/208737/
God bless.

**Comment by vladimiroltean** [comment]
I abandoned the LineageOS patch, because it turns out it is not strictly needed.
In other news, the refactoring work is done.
So hurray, I'm closing this!
